[package]
name = "client_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
domain = { path = "../domain" }
thiserror = "2.0.17"
uuid = { version = "1.19.0", features = ["v4", "fast-rng"] }
